### ISSUE TITLE
Pdf links?

### ISSUE THREAD

**Issue by githwxi** [jats-ug/translate#13]
I added html links to your translation on the ATS/Documents page:

http://www.ats-lang.org/Documents.html

Do you have pdf links (or links in other formats)? If so, please let me know
and I would really like to add those, too.

Cheers!

**Comment by master-q** [comment]
Sorry. I have no plan to publish our translations as PDF.
I would like to focus to translate the other documents.

Thanks,

**Comment by master-q** [comment]
> I added html links to your translation on the ATS/Documents page:

And we also translate your "Effective ATS Programming through Examples" into Japanese.

https://github.com/jats-ug/translate/blob/master/Manual/EffectiveATS.md

Could you add the link on the ATS/Documents page?

**Comment by githwxi** [comment]
It is added now:

http://www.ats-lang.org/Documents.html

**Comment by master-q** [comment]
Thanks!
